FROM node:22-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
COPY packages/shared/package.json ./packages/shared/
COPY packages/api/package.json ./packages/api/
RUN npm install --workspace=@weather-app/api --workspace=@weather-app/shared

COPY packages/shared ./packages/shared
COPY packages/api ./packages/api
RUN npm run build -w @weather-app/api

FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app/packages/api/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/api/node_modules ./packages/api/node_modules
COPY --from=builder /app/packages/shared ./packages/shared
COPY packages/api/package.json ./

ENV NODE_ENV=production
EXPOSE 3001

CMD ["node", "dist/src/main"]
